-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

ALTER TABLE public.leads DISABLE ROW LEVEL SECURITY;

ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "允许所有人提交线索" ON public.leads;
DROP POLICY IF EXISTS "允许匿名用户提交线索" ON public.leads;

CREATE POLICY "允许所有人提交线索" ON public.leads
FOR ALL
USING (true)
WITH CHECK (true);