-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE POLICY anon_insert_auto_articles ON articles FOR INSERT TO anon WITH CHECK (source_type = 'auto_generated'); CREATE POLICY anon_update_auto_articles ON articles FOR UPDATE TO anon USING (source_type = 'auto_generated') WITH CHECK (source_type = 'auto_generated');
