-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

DROP POLICY IF EXISTS anon_insert_auto_articles ON articles; DROP POLICY IF EXISTS anon_update_auto_articles ON articles; CREATE POLICY test_anon_insert_articles ON articles FOR INSERT TO anon WITH CHECK (true); CREATE POLICY test_anon_update_articles ON articles FOR UPDATE TO anon USING (true) WITH CHECK (true);
