-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建系统配置表
CREATE TABLE IF NOT EXISTS system_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  key VARCHAR(255) NOT NULL UNIQUE,
  value TEXT,
  description TEXT,
  category VARCHAR(100) DEFAULT 'general',
  is_encrypted BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 启用RLS
ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;

-- 创建策略：管理员可以管理所有配置
CREATE POLICY "管理员可管理系统配置" ON system_settings FOR ALL USING (auth.uid() IS NOT NULL);

-- 创建索引
CREATE INDEX idx_settings_category ON system_settings(category);
CREATE INDEX idx_settings_key ON system_settings(key);

-- 插入默认配置
INSERT INTO system_settings (key, value, description, category) VALUES
('coze_api_key', '', '扣子API密钥', 'ai'),
('coze_bot_id', '', '扣子Bot ID', 'ai'),
('auto_fetch_enabled', 'false', '自动抓取开关', 'automation'),
('auto_generate_enabled', 'false', '自动生成开关', 'automation'),
('auto_publish_enabled', 'false', '自动发布开关', 'automation'),
('fetch_interval_minutes', '60', '抓取间隔（分钟）', 'automation'),
('site_title', '有机云', '网站标题', 'site'),
('site_description', '企业微信私域流量自动化运营专家', '网站描述', 'site'),
('contact_phone', '133-1616-9107', '联系电话', 'contact'),
('contact_email', '374183167@qq.com', '联系邮箱', 'contact')
ON CONFLICT (key) DO NOTHING;