-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

DROP POLICY IF EXISTS "允许匿名用户提交线索" ON public.leads;

CREATE POLICY "允许匿名用户提交线索" ON public.leads
FOR INSERT WITH CHECK (true);