-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE public.articles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  summary TEXT,
  cover_image TEXT,
  source_url TEXT,
  source_type TEXT DEFAULT 'original',
  status TEXT DEFAULT 'draft',
  view_count INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  published_at TIMESTAMP
);

ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "允许匿名用户查看已发布文章" ON public.articles
  FOR SELECT USING (status = 'published');

CREATE POLICY "允许认证用户管理文章" ON public.articles
  FOR ALL USING (auth.role() = 'authenticated');