-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

DROP TRIGGER IF EXISTS leads_insert_notify ON leads; CREATE TRIGGER leads_insert_notify AFTER INSERT ON leads FOR EACH ROW EXECUTE FUNCTION notify_new_lead();
