-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建LOGO存储桶
INSERT INTO storage.buckets (id, name, public) VALUES
  ('site-assets', 'site-assets', true)
ON CONFLICT (id) DO NOTHING;

-- 添加LOGO和Favicon设置到system_settings表
INSERT INTO system_settings (key, value, description, category) VALUES
  ('site_logo_url', '', '网站LOGO图片URL', 'site'),
  ('site_logo_dark_url', '', '网站暗色模式LOGO图片URL', 'site'),
  ('site_favicon_url', '', '网站Favicon图片URL', 'site')
ON CONFLICT (key) DO NOTHING;

-- 设置存储桶RLS策略
CREATE POLICY "Public read site-assets" ON storage.objects
  FOR SELECT USING (bucket_id = 'site-assets');

CREATE POLICY "Admin upload site-assets" ON storage.objects
  FOR INSERT WITH CHECK (bucket_id = 'site-assets' AND auth.jwt() ->> 'email' IS NOT NULL);

CREATE POLICY "Admin delete site-assets" ON storage.objects
  FOR DELETE USING (bucket_id = 'site-assets' AND auth.jwt() ->> 'email' IS NOT NULL);