-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE OR REPLACE FUNCTION notify_new_lead() RETURNS TRIGGER AS $$ DECLARE webhook_url text := 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=37da6158-b2fa-49a2-a275-b1ebfa9c86ff'; BEGIN PERFORM net.http_post(url := webhook_url, headers := '{"Content-Type": "application/json"}'::jsonb, body := jsonb_build_object('msgtype', 'text', 'text', jsonb_build_object('content', concat_ws(E'\n', '📋 新官网线索！', '━━━━━━━━━━━━━━━━', concat('👤 姓名：', COALESCE(NEW.name, '未填写')), concat('📞 电话：', COALESCE(NEW.phone, '未填写')), concat('🏢 公司：', COALESCE(NEW.company, '未填写')), concat('📝 需求：', COALESCE(NEW.requirement, '未填写')), '🌐 来源：官网表单', concat('⏰ 时间：', to_char(NEW.created_at AT TIME ZONE 'Asia/Shanghai', 'YYYY-MM-DD HH24:MI:SS')))))); RETURN NEW; END; $$ LANGUAGE plpgsql SECURITY DEFINER;
