-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS public.testimonials (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company TEXT NOT NULL,
  avatar TEXT DEFAULT 'A',
  content TEXT NOT NULL,
  rating INTEGER DEFAULT 5,
  result TEXT NOT NULL,
  is_active BOOLEAN DEFAULT true,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;

CREATE POLICY "所有人可查看激活的案例" ON public.testimonials FOR SELECT USING (is_active = true);

CREATE POLICY "认证用户可管理案例" ON public.testimonials FOR ALL USING (auth.uid() IS NOT NULL);