-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建内容源表
CREATE TABLE IF NOT EXISTS content_sources (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  url TEXT NOT NULL,
  source_type VARCHAR(50) NOT NULL DEFAULT 'rss',
  category VARCHAR(100),
  is_active BOOLEAN DEFAULT true,
  last_fetch_at TIMESTAMP,
  fetch_interval_minutes INTEGER DEFAULT 60,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 创建原始内容表
CREATE TABLE IF NOT EXISTS raw_contents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source_id UUID REFERENCES content_sources(id) ON DELETE CASCADE,
  original_title TEXT NOT NULL,
  original_content TEXT,
  original_url TEXT NOT NULL,
  author VARCHAR(255),
  published_at TIMESTAMP,
  fetched_at TIMESTAMP DEFAULT NOW(),
  is_processed BOOLEAN DEFAULT false,
  UNIQUE(original_url)
);

-- 创建AI生成任务表
CREATE TABLE IF NOT EXISTS ai_generation_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  raw_content_id UUID REFERENCES raw_contents(id) ON DELETE CASCADE,
  status VARCHAR(50) DEFAULT 'pending',
  generated_title TEXT,
  generated_content TEXT,
  generated_summary TEXT,
  keywords TEXT[],
  error_message TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  completed_at TIMESTAMP
);

-- 创建发布任务表
CREATE TABLE IF NOT EXISTS publish_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  generation_task_id UUID REFERENCES ai_generation_tasks(id) ON DELETE CASCADE,
  article_id UUID REFERENCES articles(id) ON DELETE SET NULL,
  status VARCHAR(50) DEFAULT 'pending',
  scheduled_at TIMESTAMP,
  published_at TIMESTAMP,
  error_message TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 启用RLS
ALTER TABLE content_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_contents ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_generation_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE publish_tasks ENABLE ROW LEVEL SECURITY;

-- 创建策略：管理员可以管理所有数据
CREATE POLICY "管理员可管理内容源" ON content_sources FOR ALL USING (auth.uid() IS NOT NULL);
CREATE POLICY "管理员可管理原始内容" ON raw_contents FOR ALL USING (auth.uid() IS NOT NULL);
CREATE POLICY "管理员可管理AI任务" ON ai_generation_tasks FOR ALL USING (auth.uid() IS NOT NULL);
CREATE POLICY "管理员可管理发布任务" ON publish_tasks FOR ALL USING (auth.uid() IS NOT NULL);

-- 创建索引
CREATE INDEX idx_raw_contents_source ON raw_contents(source_id);
CREATE INDEX idx_raw_contents_processed ON raw_contents(is_processed);
CREATE INDEX idx_ai_tasks_status ON ai_generation_tasks(status);
CREATE INDEX idx_publish_tasks_status ON publish_tasks(status);