-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 添加新字段到 articles 表
ALTER TABLE articles ADD COLUMN IF NOT EXISTS slug TEXT UNIQUE;
ALTER TABLE articles ADD COLUMN IF NOT EXISTS category TEXT DEFAULT '未分类';
ALTER TABLE articles ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';
ALTER TABLE articles ADD COLUMN IF NOT EXISTS seo_title TEXT;
ALTER TABLE articles ADD COLUMN IF NOT EXISTS seo_description TEXT;
ALTER TABLE articles ADD COLUMN IF NOT EXISTS seo_keywords TEXT[] DEFAULT '{}';
ALTER TABLE articles ADD COLUMN IF NOT EXISTS scheduled_at TIMESTAMPTZ;

-- 更新现有数据的 slug
UPDATE articles SET slug = LOWER(REGEXP_REPLACE(REGEXP_REPLACE(title, '[^a-zA-Z0-9\u4e00-\u9fa5]', '-', 'g'), '-+', '-', 'g')) || '-' || FLOOR(RANDOM() * 9000 + 1000)::TEXT WHERE slug IS NULL;

-- 创建分类表
CREATE TABLE IF NOT EXISTS categories (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  sort INT DEFAULT 0
);

-- 插入默认分类
INSERT INTO categories (name, slug, sort) VALUES
  ('AI私域', 'ai-private', 1),
  ('客服Agent', 'cs-agent', 2),
  ('案例分析', 'cases', 3),
  ('行业洞察', 'insights', 4)
ON CONFLICT (name) DO NOTHING;

-- 创建存储桶（通过插入数据方式）
INSERT INTO storage.buckets (id, name, public) VALUES
  ('article-covers', 'article-covers', true),
  ('article-media', 'article-media', true)
ON CONFLICT (id) DO NOTHING;

-- 更新 RLS 策略
DROP POLICY IF EXISTS "Public read published" ON articles;
CREATE POLICY "Public read published" ON articles
  FOR SELECT USING (status = 'published');

DROP POLICY IF EXISTS "Admin full access" ON articles;
CREATE POLICY "Admin full access" ON articles
  FOR ALL USING (auth.jwt() ->> 'email' IS NOT NULL);

-- 为 storage 创建 RLS 策略
CREATE POLICY "Public read article-covers" ON storage.objects
  FOR SELECT USING (bucket_id = 'article-covers');

CREATE POLICY "Public read article-media" ON storage.objects
  FOR SELECT USING (bucket_id = 'article-media');

CREATE POLICY "Admin upload article-covers" ON storage.objects
  FOR INSERT WITH CHECK (bucket_id = 'article-covers' AND auth.jwt() ->> 'email' IS NOT NULL);

CREATE POLICY "Admin upload article-media" ON storage.objects
  FOR INSERT WITH CHECK (bucket_id = 'article-media' AND auth.jwt() ->> 'email' IS NOT NULL);