-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE OR REPLACE FUNCTION notify_new_lead() RETURNS TRIGGER AS $$ DECLARE edge_function_url text := 'https://nzvgai6r8knh.functions.meoo.host/notify-wechat'; BEGIN PERFORM net.http_post(url := edge_function_url, headers := '{"Content-Type": "application/json"}'::jsonb, body := jsonb_build_object('name', NEW.name, 'company', NEW.company, 'phone', NEW.phone, 'requirement', NEW.requirement, 'created_at', NEW.created_at)); RETURN NEW; END; $$ LANGUAGE plpgsql SECURITY DEFINER;
