/**
 * 🚨 此文件由 CloudEnableTool 自动生成，请勿手动修改！
 * This file is auto-generated by CloudEnableTool. Do not edit manually!
 */

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export function getSupabaseUrl(): string {
  // 通过 EdgeOne CDN 子域名回源到 Supabase，国内可达，无需边缘函数
  // sbapi.fenyai.com → EdgeOne 站点加速 → 回源 nzvgai6r8knh.supabase.co
  return 'https://sbapi.fenyai.com';
}

export const supabaseUrl = getSupabaseUrl();
export const supabaseAnonKey = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzc2NTA2NTM0LCJleHAiOjEzMjg3MTQ2NTM0fQ.ifqqV_uNL2xJOZ34kOgu5Ss2RqUyImjPjfEqD0wvTbo';

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});
